services:
  traefik_adminer:
    container_name: traefik_adminer
    image: adminer
    ports:
      - '8081:8080'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-adminer.rule=Host(`adminer.traefik.com`)'
      - 'traefik.http.routers.traefik-adminer.entrypoints=web'
      - 'traefik.http.services.traefik-adminer.loadbalancer.server.port=8081'
    healthcheck:
      test: ['CMD', 'sh', '-c', 'ps aux | grep "[p]hp -S \\[::\\]:8080"']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  traefik_gateway:
    name: traefik_gateway
    external: true
  traefik_database:
    name: traefik_database
    external: true
