services:
  traefik_adminer:
    container_name: traefik_adminer
    image: adminer
    ports:
      - 8082:8080
    networks:
      - traefik_database
      - traefik_gateway

networks:
  traefik_gateway:
    name: traefik_gateway
    driver: bridge
    external: true
  traefik_database:
    name: traefik_database
    driver: bridge
    external: true
