services:
  traefik_backend:
    container_name: traefik_backend
    build:
      context: .
      dockerfile: .docker/laravel/Dockerfile
    volumes:
      - ./.docker/laravel/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./.docker/laravel/supervisor/queue-worker.conf:/etc/supervisor/conf.d/queue-worker.conf
      - ./.docker/laravel/supervisor/php-fpm.conf:/etc/supervisor/conf.d/php-fpm.conf
      - ./.docker/laravel/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./code:/var/www:delegated
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.laravel.rule=Host(`localhost`)'
      - 'traefik.http.routers.laravel.entrypoints=web'
      - 'traefik.http.services.laravel.loadbalancer.server.port=9000'
    networks:
      - traefik_webserver
      - traefik_database
    restart: unless-stopped

networks:
  traefik_webserver:
    name: traefik_webserver
    external: true
  traefik_database:
    name: traefik_database
    external: true
