services:
  traefik_backend:
    container_name: traefik_backend
    build:
      context: .
      dockerfile: .docker/laravel/Dockerfile
    volumes:
      - ./.docker/laravel/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./.docker/laravel/supervisor/queue-worker.conf:/etc/supervisor/conf.d/queue-worker.conf
      - ./.docker/laravel/supervisor/php-fpm.conf:/etc/supervisor/conf.d/php-fpm.conf
      - ./.docker/laravel/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./backend:/var/www:delegated
    networks:
      - traefik_webserver
      - traefik_database
    healthcheck:
      test: ['CMD', 'php-fpm', '-t']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  traefik_webserver:
    name: traefik_webserver
    driver: bridge
  traefik_database:
    name: traefik_database
    driver: bridge
