services:
  traefik_mysql:
    container_name: traefik_mysql
    build:
      context: ./.docker/mysql
    hostname: ${MYSQL_HOST}
    environment:
      - APP_ENV=${MYSQL_APP_ENV}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/db:/docker-entrypoint-initdb.d/
      - ./.docker/mysql/config/my.cnf:/etc/mysql/my.cnf
    networks:
      - traefik_database
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
  traefik_database:
    name: traefik_database
    driver: bridge

volumes:
  mysql:
    name: traefik_mysql_data
