services:
  traefik_server:
    container_name: traefik_server
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - '8001:8001'
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/config/app.conf:/etc/nginx/conf.d/app.conf
      - ./.docker/nginx/logs:/var/log/nginx
      - ./code:/var/www/backend
    networks:
      - traefik_webserver
      - traefik_gateway
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-webserver.rule=Host(`traefik.com`)'
      - 'traefik.http.routers.traefik-webserver.entrypoints=web'
      - 'traefik.http.services.traefik-webserver.loadbalancer.server.port=8001'
networks:
  traefik_webserver:
    name: traefik_webserver
    driver: bridge
  traefik_gateway:
    name: traefik_gateway
    driver: bridge
    external: true
