services:
  traefik_gateway:
    container_name: traefik_gateway
    image: traefik:v3.4
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--api=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=traefik_gateway'
      - '--entrypoints.web.address=:80'
      - '--log.level=DEBUG'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-dashboard.rule=Host(`dashboard.traefik.com`)'
      - 'traefik.http.routers.traefik-dashboard.entrypoints=web'
      - 'traefik.http.routers.traefik-dashboard.service=api@internal'
    networks:
      - traefik_gateway

networks:
  traefik_gateway:
    name: traefik_gateway
    driver: bridge
