services:
  traefik_gateway:
    container_name: traefik_gateway
    image: traefik:v3.4
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/traefik/dynamic/:/dynamic:ro
      - ./.docker/traefik/certs:/certs:ro
    command:
      - '--api=true'
      - '--api.dashboard=true'

      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'

      - '--entrypoints.websecure.http.tls=true'
      - '--entryPoints.websecure.address=:443'

      - '--providers.docker.network=traefik_gateway'

      - '--providers.file.filename=/dynamic/tls.yaml'

      - '--ping=true'

      - '--log.filePath=/var/log/traefik/traefik.log'
      - '--log.level=DEBUG'

      - '--accesslog.format=json'
      - '--accesslog.filepath=/var/log/traefik/access.log'

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`dashboard.traefik.com`)'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.service=api@internal'

      - 'traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$xfWwdkfd$$2FQ5CSWuGYeCwzwr9H5Zt1'
      - 'traefik.http.routers.dashboard.middlewares=dashboard-auth@docker'
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 10s
      retries: 5

    networks:
      - traefik_gateway

networks:
  traefik_gateway:
    name: traefik_gateway
    driver: bridge
