services:
  traefik_gateway:
    container_name: traefik_gateway
    image: traefik:v3.4
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/traefik/dynamic/:/dynamic:ro
      - ./.docker/traefik/certs:/certs:ro
    command:
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.tls=true'
      - '--ping'

      - '--providers.file.filename=/dynamic/tls.yaml'

      # Providers
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=traefik_gateway'

      # API & Dashboard
      - '--api.dashboard=true'
      - '--api.insecure=false'

      - '--log.level=INFO'
      - '--accesslog=true'
      - '--metrics.prometheus=true'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`dashboard.traefik.com`)'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.tls=true'

      # Basic‑auth middleware
      - 'traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$TIW//mDW$$H9zOc6EoMI4oaBkR3RPbY1'
      - 'traefik.http.routers.dashboard.middlewares=dashboard-auth@docker'
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 10s
      retries: 5

    networks:
      - traefik_gateway

networks:
  traefik_gateway:
    name: traefik_gateway
    driver: bridge
