http:
  routers:
    traefik-webserver:
      rule: 'Host(`traefik.com`)'
      service: traefik-webserver
      entryPoints:
        - web
    traefik-dashboard:
      rule: 'Host(`dashboard.traefik.com`)'
      service: dashboard
      entryPoints:
        - web
    traefik-adminer:
      rule: 'Host(`adminer.traefik.com`)'
      service: traefik-adminer
      entryPoints:
        - web
  services:
    traefik-webserver:
      loadBalancer:
        servers:
          - url: 'http://traefik_server:8001'
    dashboard:
      loadBalancer:
        servers:
          - url: 'http://traefik_gateway:8080'
    traefik-adminer:
      loadBalancer:
        servers:
          - url: 'http://traefik_adminer:8080'
